### ISSUE TITLE
Support to link multiple customerscc

### ISSUE THREAD

**Issue by ppacher** [tierklinik-dobersberg/cis#3]
## Epic Context

With support for CardDAV addressbooks as a customer source there's also an increased need on managing and working with customers that are present in multiple sources. Since call-log records, patient data, etc ... are bound to a single customer record (source/cid) we need a way to aggregate this information for customers that are available in different sources. Also, we need to specify how the user/operator gets informed about possibly related customer records, how this relation is determined and what actions are feasible.

## Proposed Solution

Implement a "related customer" management solution by linking customers to each other with one being the primary that is used for various customer-related features like calllogs, 3CX-CRM integration and calendar integration.

Right now, the following resources/APIs are bound to single customers and will need a solution when we introduce customer links:
- Customer Records (how should importers handle linked customers?)
- Patient Records
- Voicemails
- 3CX CRM integration
- Call-logs
- Calendar Events (not yet used but will be)
- Comments

### Customer Sources

Right now the "customer source" is a single string that only groups customer from the same importer. Though, it does not (yet) have any special meaning. For "linking" customers we should rework the identifier to actually point to a "source type" registration that  defines capabilities of the source like deleting, creating or updating customer records. This will move us away from the current "customers are read-only" view. Although not directly required for this proposal, a `delete` capability in, for example, the CardDAV source would allow users to get rid of duplicated entries within the same source.

### Suggestions

To guide users through the linking of related customers a "suggestion" feature should be implemented. On top of the already existing `runtime/tasks` a new task should be added to searches for customers that likely belong together. For those customers, a `suggestion` is created and stored in the cache, preferably at a persistent location (i.e. under the mongodb mount). 
Those suggestions should be displayed to allowed users in the UI. Suggestions can be applied (i.e. linking customers), deleted (so they get re-created when the task re-runs) or marked as "invalid" in which case they will never show up again.

While being relatively simple for this proposal, the suggestion feature should definitely get a dedicated - versioned - API scope at `/api/suggestions/v1` or similar. Also, the implementation should take care that different suggestion types might be added later. Examples for such types might be prompting user for additional customer data or maybe inform a user about a customer that might wait for being called back (like when we have multiple consecutive missed calls from one customer).

### Customer Links

Customer links are implemented using a `LinkedTo` property that holds the mongo-db document ID of the primary customer. A dedicated index should be created so lookups for the primary customer are fast. Note that in theory, a customer may be a primary as well as a secondary customer at the same time. This should be avoided so customers can only be either a primary or a secondary one. This limitation should make lookups of the primary customer as well as syncing easier and prevents cycles.

The following sections should outline the important aspects and considerations for CRUD operations on customers and how primary or secondary customers should be handled.

#### Creating new customers

Right now customers can only be created by importers/customer sources so automatic linking is not possible as it requires
manual user action on a "linkable" suggestion. Thus, creating customers does not require any special care in regards to customer links.

#### Updating existing customers

When customers are updated either by the respective customer source or by manual user action the current link state of the customer must be persisted and must not be changed or removed (expect the user actually want's to remove the link). Syncing of changes to linked customers of other sources is not part of this specification and will be covered in more detail by #4 (which depends on this epic or the ground work)

### User-Interface

- Display suggestions and allow dedicated actions
- Allow customer links to be removed again (on the customer view)

## Tasks

From the above proposal, the following is a rough list of to-dos to get it working:

- [X] Customer Source-Types with capabilities
- [X] Delete customer support for CardDAV
- [X] Suggestion API
- [X] Dedicated permissions for suggestion API
- [X] Linkable-Customer suggestion type and task
- [ ] Handle call-records correctly
- [ ] Handle 3CX CRM queries correctly
- [ ] Update user interface
